// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cn3m7j05Y9nxH6o8wzWcGJiEZU2EnTU',
    appId: '1:834692370765:web:e68a4daa69ce1733fca704',
    messagingSenderId: '834692370765',
    projectId: 'componentesflutter-990db',
    authDomain: 'componentesflutter-990db.firebaseapp.com',
    storageBucket: 'componentesflutter-990db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Pjn987NKAhhm9juKhrPzJFuRCp9P2is',
    appId: '1:834692370765:android:05d00836ac18116afca704',
    messagingSenderId: '834692370765',
    projectId: 'componentesflutter-990db',
    storageBucket: 'componentesflutter-990db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4W-2KRbISUrrauOlC91RaWuFp1e2aMQw',
    appId: '1:834692370765:ios:299360a2ea599ffffca704',
    messagingSenderId: '834692370765',
    projectId: 'componentesflutter-990db',
    storageBucket: 'componentesflutter-990db.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
